language: node_js
node_js:
- 14
branches:
  only:
  - master
  - travis
before_deploy:
- npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    repo: americanbible/scripture-styles
    branch: master
- provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: assets.api.bible
  local-dir: dist
  on:
    repo: americanbible/scripture-styles
    branch: master
- provider: script
  skip_cleanup: true
  script: cd previewer && npm install && npm run deploy-storybook -- --ci
  on:
    repo: americanbible/scripture-styles
    branch: master
