language: node_js
node_js:
- 14
branches:
  only:
  - master
  - travis
before_deploy:
- npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    repo: americanbible/scripture-styles
    branch: master
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAW3FERPLDOJJBHNUU
  secret_access_key:
    secure: Vhe+8kzM97gVgq/wjMEv1G5oLcl3SMUY03VYWg+Gbn5TULNSOFmWVskEx+HEIamPXTO6D2RpgUFxouDsWqjskBGbLD1lwyE2C6+q4qDIEP0tqxR+W2rr78KIvTgwTWida1Kyg6BQhLOD7LaMB4YqvvBBJLiE0l1bjYCI9a8FHio=
  bucket: assets.api.bible
  local-dir: dist
  on:
    repo: americanbible/scripture-styles
    branch: master
- provider: script
  skip_cleanup: true
  script: cd previewer && npm install && npm run deploy-storybook -- --ci
  on:
    repo: americanbible/scripture-styles
    branch: master
