language: node_js
node_js:
- 11
branches:
  only:
  - master
  - travis
before_deploy:
- npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    repo: americanbible/scripture-styles
    branch: master
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAW3FERPLDOJJBHNUU
  secret_access_key:
    secure: cboyxA6i659/qN/xqSEdBWtWwD/0mM0blhMpyR7V5G1BMzWOPDv+mA7JM+mUoi/HnWn57d3ghFOZgndsRjvLBc0LJS+NoYwTyjnNEWmkAcvBIsPp7kW1p9BQeqSQ1riLHDFpXboWKbEEuSzEhSN8mniEd1QR/9dhnttzAEhpInQ=
  bucket: 'assets.api.bible'
  local-dir: dist
  on:
    repo: americanbible/scripture-styles
    branch: master
- provider: script
  skip_cleanup: true
  script: cd previewer && npm install && npm run deploy-storybook -- --ci
  on:
    repo: americanbible/scripture-styles
    branch: master

